/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersIdRouteImport } from './routes/chapters.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersIdRoute = ChaptersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChaptersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/course': typeof CourseRoute
  '/resources': typeof ResourcesRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/resources': typeof ResourcesRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/course': typeof CourseRoute
  '/resources': typeof ResourcesRoute
  '/chapters/$id': typeof ChaptersIdRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters'
    | '/course'
    | '/resources'
    | '/chapters/$id'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course' | '/resources' | '/chapters/$id' | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/chapters'
    | '/course'
    | '/resources'
    | '/chapters/$id'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  CourseRoute: typeof CourseRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/chapters/$id': {
      id: '/chapters/$id'
      path: '/$id'
      fullPath: '/chapters/$id'
      preLoaderRoute: typeof ChaptersIdRouteImport
      parentRoute: typeof ChaptersRoute
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersIdRoute: typeof ChaptersIdRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersIdRoute: ChaptersIdRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  CourseRoute: CourseRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
